### ISSUE TITLE
建议将 ghproxy.com 代理换为 mirror.ghproxy.com

### ISSUE THREAD

**Issue by stilleshan** [wuye999/myScripts#11]
作者你好,我是 ghproxy.com 的站长.

我站主要为方便国内网络无法访问 GitHub 的正常需求的代理.

最近这几个月每日数千万的请求 80% 都来源于各种 jd 脚本,已经影响到正常使用,特别是今天有两小时突发请求暴增几百万条是来源于你的项目.为了不影响用户使用,我并没有采取一些屏蔽设置,而是新增了服务器负载均衡...目前请求已恢复正常.

建议将各种类似以下脚本中的代理站链接换为 https://mirror.ghproxy.com , 将会使用 jsDelivr 的 CDN 网络代理,同样能满足使用需求.
```
url = 'https://ghproxy.com/https://raw.githubusercontent.com/wuye999/myScripts/main/sendNotify.py'
```

**Comment by wuye999** [comment]
> 作者你好,我是 ghproxy.com 的站长.
> 
> 我站主要为方便国内网络无法访问 GitHub 的正常需求的代理.
> 
> 最近这几个月每日数千万的请求 80% 都来源于各种 jd 脚本,已经影响到正常使用,特别是今天有两小时突发请求暴增几百万条是来源于你的项目.为了不影响用户使用,我并没有采取一些屏蔽设置,而是新增了服务器负载均衡...目前请求已恢复正常.
> 
> 建议将各种类似以下脚本中的代理站链接换为 https://mirror.ghproxy.com , 将会使用 jsDelivr 的 CDN 网络代理,同样能满足使用需求.
> 
> ```
> url = 'https://ghproxy.com/https://raw.githubusercontent.com/wuye999/myScripts/main/sendNotify.py'
> ```

好的
