### ISSUE TITLE
膨胀脚本秀出天际

### ISSUE THREAD

**Issue by 1589089997** [wuye999/myScripts#13]
作者你的膨胀脚本是默认领取红包，放弃膨胀，我是真的服了，你这运行逻辑干嘛要在脚本里加助力两个字呢。。。
![0AFBC7E2-A8EC-471C-8432-A93CF00B8AB8](https://user-images.githubusercontent.com/84494713/141122087-dede8c02-64a2-4675-9efe-7a4e5f96c835.jpeg)
![9820EB89-0E7E-4677-A2B3-8B818989BEAC](https://user-images.githubusercontent.com/84494713/141122107-9b0dc54e-e444-4c81-997c-2b8e98d87390.jpeg)
![80EE7302-E93A-4727-AA54-317C5779079A](https://user-images.githubusercontent.com/84494713/141122113-ce993354-cfc5-4115-8612-cd172f402eaa.jpeg)

**Comment by wuye999** [comment]
![image](https://user-images.githubusercontent.com/79479594/141123132-d8098a53-4199-44dc-ac59-57089bb62b41.png)

**Comment by 1589089997** [comment]
大哥你个定时和后面的注释在哪，我完全没找到。。。😩
