### ISSUE TITLE
jd_angryKoi考不考虑助力完指定账号后自动停止啊？

### ISSUE THREAD

**Issue by xsj684135** [wuye999/myScripts#15]

**Comment by wuye999** [comment]
他本来就是只助力指定账号啊

**Comment by xsj684135** [comment]
说错啦，会自动开乘客包... 会开好多包

账号 jd_BqaTLTwCDzdv 开红包
您还未发起红包，邀请好友帮拆吧

账号 %E5%91%BC%E5%91%BC%E5%91%BC-%E5%91%BC%E5%91%BC%E5%91%BC-3 开红包
您还未发起红包，邀请好友帮拆吧

账号 538568530-270419 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_6896d58063b5b 开红包
您还未发起红包，邀请好友帮拆吧

账号 %E5%91%BC%E5%91%BC%E5%91%BC-%E5%91%BC%E5%91%BC%E5%91%BC-2 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_KWzJbjBiNzVa 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_XkkBwgOGqtWE 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_XSbPgCYJnhio 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_gcqCugBQukWL 开红包
您拆红包次数已用光，继续加油哦

账号 jd_FxHStRvzqEXF 开红包
您拆红包次数已用光，继续加油哦

账号 %E8%BF%85%E5%AE%9D%E5%AE%9D5 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_rsBNjEyyFIvn 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_YlGTCuwMbshy 开红包
您还未发起红包，邀请好友帮拆吧

账号 cch-2 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_6cfbfae2b155f 开红包
您拆红包次数已用光，继续加油哦

账号 ilt-1 开红包
您还未发起红包，邀请好友帮拆吧

账号 jd_kGVviAJDpLPa 开红包
您还未发起红包，邀请好友帮拆吧

账号 18318997643_p 开红包
您拆红包次数已用光，继续加油哦

账号 jd_66bd11bc9fbf5 开红包
您拆红包次数已用光，继续加油哦

账号 jd_6f075750c2aa6 开红包
您拆红包次数已用光，继续加油哦

账号 jd_58f329b18fbaa 开红包
您拆红包次数已用光，继续加油哦

账号 jd_6dcf1d1dad55c 开红包
您拆红包次数已用光，继续加油哦

账号 jd_63346d8695727 开红包
您拆红包次数已用光，继续加油哦

账号 ctt13610106164 开红包
您拆红包次数已用光，继续加油哦

账号 jd_4a19942c3d7af 开红包
您拆红包次数已用光，继续加油哦

账号 jd_pymGIymrmiQp 开红包
您拆红包次数已用光，继续加油哦

账号 jd_556f06bd7e77c 开红包
您拆红包次数已用光，继续加油哦

账号 jd_NfPinKlyjTgX 开红包
您拆红包次数已用光，继续加油哦

账号 wdqoVkVilNvMcN 开红包
您拆红包次数已用光，继续加油哦

账号 jd_cBBwCxJDCxDF 开红包
恭喜您，获得红包 0.12

账号 jd_cBBwCxJDCxDF 开红包
您拆红包次数已用光，继续加油哦

账号 jd_57213288f686d 开红包
恭喜您，获得红包 0.12

账号 jd_57213288f686d 开红包
您拆红包次数已用光，继续加油哦

账号 jd_4a9db143aae3a 开红包
您拆红包次数已用光，继续加油哦

**Comment by wuye999** [comment]
你是说改成只开指定账号的包？
