### ISSUE TITLE
请问沃邮箱登陆Url怎么获取呐？

### ISSUE THREAD

**Issue by EchoChan314** [wuye999/myScripts#17]
我关注微信公众号后抓包还是没找到 https://nyan.mail.wo.cn/cn/sign/index/index?mobile 开头的 URL

**Comment by wuye999** [comment]
> 我关注微信公众号后抓包还是没找到 https://nyan.mail.wo.cn/cn/sign/index/index?mobile 开头的 URL

可能是在某请求的响应体里有这么个url

**Comment by a502747245** [comment]
你在公众号里面，所有的东西都点一遍，你就抓到了
