### ISSUE TITLE
发财挖宝领奖励有问题

### ISSUE THREAD

**Issue by KuHai-A** [wuye999/myScripts#5]
提示信息如下：
开始领取奖励
参数与当前场次不一致

看样子是场次id在前面挖宝时循环到了3，但是开始领奖时没有从1重新开始

**Comment by wuye999** [comment]
好的，已更新

**Comment by wuye999** [comment]
好的，已更新

> 提示信息如下： 开始领取奖励 参数与当前场次不一致
> 
> 看样子是场次id在前面挖宝时循环到了3，但是开始领奖时没有从1重新开始
