### ISSUE TITLE
财富岛提现wy_debug_url不太对~

### ISSUE THREAD

**Issue by boopzk22** [wuye999/myScripts#7]
财富岛提现wy_debug_url不太对~

**Comment by wuye999** [comment]
已更新api

**Comment by boopzk22** [comment]
> 已更新api

好像还是不对

**Comment by boopzk22** [comment]
> 已更新api

jsonpCBKN({
   "iRet" : 2011,
   "sErrMsg" : "奖品已更新，刷新下页面吧~"

**Comment by wuye999** [comment]
> > 已更新api
> 
> jsonpCBKN({ "iRet" : 2011, "sErrMsg" : "奖品已更新，刷新下页面吧~"

已更新，但不知到对不

**Comment by w123113** [comment]
Traceback (most recent call last):
  File "raw_jd_jd_jxcfd_cash111.py", line 217, in <module>
    asyncio.run(asyncclass())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "raw_jd_jd_jxcfd_cash111.py", line 201, in asyncclass
    await asyncio.wait(tasks)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 413, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.



大佬，这是什么原因呢？

**Comment by wuye999** [comment]
> Traceback (most recent call last): File "raw_jd_jd_jxcfd_cash111.py", line 217, in asyncio.run(asyncclass()) File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "raw_jd_jd_jxcfd_cash111.py", line 201, in asyncclass await asyncio.wait(tasks) File "/usr/lib/python3.8/asyncio/tasks.py", line 413, in wait raise ValueError('Set of coroutines/Futures is empty.') ValueError: Set of coroutines/Futures is empty.
> 
> 大佬，这是什么原因呢？

没填 wy_debug_pin吧
